#!/bin/bash -e

source ./install_0_setup


# Hadoop Pre-run Setup
# At this point the configuration files created in /etc/hadoop/conf.tessera on node001 should be copied to all other nodes. Any future changes to any configuration files should be done on node001 and then copied from there to all other nodes.
# Note: In the event that some nodes have different number of drives, or the paths to those drives differ, or they have a different number of CPUs, different amounts of RAM, etc. then separate, independent hdfs-site.xml and yarn-site.xml files may be necessary on each node.

if [ `hostname` = "$monashNamenode" ]
then

  # Next we format the new HDFS filesystem before actually starting the NameNode service for the first time. This is done on the NameNode (node001) only. It must be done as the user “hdfs”:
  sudo -u hdfs hdfs namenode -format

  # make sure things are shut off
  sudo service hadoop-hdfs-namenode stop
  # Manually start hdfs first by starting the NameNode service on node001:
  sudo service hadoop-hdfs-namenode start
elif [ `hostname` = "$monashSecondaryNamenode" ]
then
  # make sure things are shut off
  sudo service hadoop-hdfs-secondarynamenode stop
  # manually start secondary name node
  sudo service hadoop-hdfs-secondarynamenode start
fi

# Then start the datanode service on node002 - node005 by typing this on each of them one at a time:
if [ `hostname` = "$monashFrontend" ]
then
  echo "do nothing" > /dev/null
else
  # make sure things are shut off
  sudo service hadoop-hdfs-datanode stop
  # manually start data node
  sudo service hadoop-hdfs-datanode start
fi



# wait unti all have finished up to here
